spring:
  datasource:
    url: jdbc:mysql://localhost:3306/college
    password: 12102021
    username: root
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          globally_quote_identifiers: true
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
  sql:
    init:
      mode: never
